version: '3'
services:
  web:
    # Apahce + PHP WebServer.
    build:
      context: ./DOCKER_FILE_CONTEXT
      args:
        VERSION: $PHP_VERSION
        HOSTNAME: $HOSTNAME
      dockerfile: docker.dockerfile
    environment:
      XDEBUG_HOST: ${XDEBUG_HOST}
    image: $PROJECT_NAME:$PROJECT_VERSION
    restart: always
    ports:
      - "${WEB_EXPOSED_PORT}80"
      - "${WEB_EXPOSED_PORT_SSL}443"
    links:
      - mysql
      - psql
    volumes:
      # App Code
      - ../app/:/code
      # Apache main Conf
      - ./server.conf:/etc/apache2/sites-available/000-default.conf
      # PHP main Conf
      - ./php.ini:/etc/php_config/apache2/conf.d/01-custom.ini
      # Persistent Log of Apache Server
      - ../log/apache2/:/var/log/apache2/
      # APT sources.list
      - ./DOCKER_FILE_CONTEXT/sources.list:/etc/apt/sources.list
  psql:
    # Postgresql Container
    image: postgres:$POSTGRES_VERSION
    volumes:
      # Persistent Data Volume
      - ../database/postgresql:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_EXPOSED_PORT}5432"
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      PGDATA: /var/lib/postgresql/data/$PROJECT_NAME
  mysql:
    # MySql Container.
    image: mysql:$MYSQL_VERSION
    volumes:
      # Persistent Data Volume
      - ../database/mysql/$PROJECT_NAME:/var/lib/mysql
      # Custom CNF file.
      - ./mysql.cnf:/etc/mysql/conf.d/01-custom.cnf
    ports:
      - "${MYSQL_EXPOSED_PORT}3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
