version: '3'
services:
  nginx:
    # Nginx WebServer. links to PHP Container.
    image: nginx:$NGINX_VERSION
    ports:
      - "${NGINX_EXPOSED_PORT}80"
      - "${NGINX_EXPOSED_PORT_SSL}443"
    links:
      - php
      - psql
      - mysql
    restart: always
    volumes:
      # App Code. Same as PHP Container
      - ../:/code
      # Nginx main Conf.
      - ./server.conf:/etc/nginx/conf.d/default.conf
      # Persistent Log of Nginx Server
      - ./LOG/nginx:/var/log/nginx
  php:
    # PHP Container. links to Database Containers.
    build:
      context: ./DOCKER_FILE_CONTEXT
      args:
        VERSION: ${PHP_VERSION}
      dockerfile: docker.dockerfile
    image: $PROJECT_NAME:$PROJECT_VERSION
    environment:
      XDEBUG_HOST: ${XDEBUG_HOST}
    volumes:
      # App Code. Same as Nginx Container
      - ../:/code
      # PHP config file
      - ./php.ini:/usr/local/etc/php/conf.d/01-custom.ini
      # Persistent Log of PHP-FPM
      - ./LOG/nginx:/var/log/nginx
  psql:
    # Postgresql Container
    image: postgres:$POSTGRES_VERSION
    volumes:
      # Persistent Data Volume
      - ./DB/postgresql:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_EXPOSED_PORT}5432"
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      PGDATA: /var/lib/postgresql/data/$PROJECT_NAME
  mysql:
    # MySql Container.
    image: mysql:$MYSQL_VERSION
    volumes:
      # Persistent Data Volume
      - ./DB/mysql/$PROJECT_NAME:/var/lib/mysql
      # Custom CNF file.
      - ./mysql.cnf:/etc/mysql/conf.d/01-custom.cnf
    ports:
      - "${MYSQL_EXPOSED_PORT}3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
